### ISSUE TITLE
Make an "install script"

### ISSUE THREAD

**Issue by cynicsketch** [cynicsketch/nix-mineral#2]
Nothing fancy needs to be done. People will need to edit the overrides themselves anyways, import the module themselves anyways, but a simple bash script to quickly copy everything where it needs to go included with the releases would be nice.

**Comment by cynicsketch** [comment]
Unnecessary with flakes. Closing due to redundancy.

**Comment by wyyllou** [comment]
> Unnecessary with flakes. Closing due to redundancy.

Technically there is a way to do a similar thing in your configuration without flakes, i think with fetchTarball or fetchUrl to fetch the module flakelessly and without putting it in your own repo locally or having to redownload the whole thing, just changing a hash and a commit when it updates, would you like me to add documentation for that as well?

**Comment by cynicsketch** [comment]
> Technically there is a way to do a similar thing in your configuration without flakes, i think with fetchTarball or fetchUrl to fetch the module flakelessly and without putting it in your own repo locally or having to redownload the whole thing, just changing a hash and a commit when it updates, would you like me to add documentation for that as well?

That would be nice to have documentation for, since it would be considerably smoother than the current suggested process of unzipping/copying.
