### ISSUE TITLE
"proc: Bad value for 'gid'"

### ISSUE THREAD

**Issue by Laski** [cynicsketch/nix-mineral#20]
After applying the current (477ef3395dc6fd69237d717edcc6f4274364b745) version via zip-downloading and importing, and then
`sudo nixos-rebuild switch` a reboot fails with:

```
proc: Bad value for 'gid'
mount: mounting proc on /proc failed: Invalid argument
tee: /proc/self/fd/8: No such file or directory
```

Commenting out this lines:
```

    # Hide processes from other users except root, may cause breakage.
    # See overrides, in desktop section.
    #"/proc" = {
    #  fsType = "proc";
    #  device = "proc";
    #  options = [
    #    "nosuid"
    #    "nodev"
    #    "noexec"
    #    "hidepid=2"
    #    "gid=proc"
    #  ];
    #};
  };

  # Add "proc" group to whitelist /proc access and allow systemd-logind to view
  # /proc in order to unbreak it.
  #users.groups.proc = { };
  #systemd.services.systemd-logind.serviceConfig.SupplementaryGroups = [ "proc" ];
```

fixes it. It seems to dislike the "gid=proc" parameter (perhaps the group is created afterwards)?

BTW this is the first time I see a group being referred by name (and not id) in mount parameters.

I'm using `stateVersion=24.05`.

**Comment by cynicsketch** [comment]
Unable to reproduce on my machine. Rebuild for me works fine and so does the mount, where nix automatically replaces the group name with the gid number once the group is created with `users.groups.proc = { };`

```
[user@host:~]$ mount | grep /proc
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime,gid=987,hidepid=ptraceable)

[user@host:~]$```

I'll try to see if I can reproduce it in a VM.

**Comment by cynicsketch** [comment]
Issue reproduced in a fresh install on a new NixOS 24.05 VM. Unclear why so far?

**Comment by cynicsketch** [comment]
Please bear with the process, since there are currently some outstanding problems with the current implementation and a "stable" release is pending an [initial rewrite](https://github.com/cynicsketch/nix-mineral/pull/19).

**Comment by cynicsketch** [comment]
> I'm using `stateVersion=24.05`.

Are you on NixOS 24.05, per chance?

This might have something to do with the version you're on. The boot failure occured in my 24.05 VM, but not on my unstable (24.11) system, and it seems likely that other users are using flakes which also forces upgrading to unstable.

If this is the case, then there's presumably nothing I can do other than advise that all users run on 24.11+ as 24.05 is soon to reach EOL and unlikely to receive any upstream updates anymore as development focuses on the next version.

**Comment by Laski** [comment]
Thanks for taking the time to see this!

> Are you on NixOS 24.05, per chance?

I think so.

> If this is the case, then there's presumably nothing I can do other than advise that all users run on 24.11+ as 24.05 is soon to reach EOL and unlikely to receive any upstream updates anymore as development focuses on the next version.

Oh cool. I'm pretty new to NixOS so I didn't know the versions had so short timespan (I'm assuming 24.05 came out on may? and we're in august).

However if this is not a problem in the new version (probably a kernel upgrade that make the 'gid' accept strings?) I'll close this as "can't reproduce". Perhaps you can update the README with a compatibility notice?

**Comment by nakibrayan3** [comment]
I am using nixpkgs-unstable, and I updated my stateVersion to `24.11`, but the problem is till present?

**Comment by cynicsketch** [comment]
> I am using nixpkgs-unstable, and I updated my stateVersion to `24.11`, but the problem is till present?

https://github.com/systemd/systemd/issues/16896

Just to rule this out, what kernel version are you running?

**Comment by nakibrayan3** [comment]
> > I am using nixpkgs-unstable, and I updated my stateVersion to `24.11`, but the problem is till present?
> 
> [systemd/systemd#16896](https://github.com/systemd/systemd/issues/16896)
> 
> Just to rule this out, what kernel version are you running?

Linux 6.6.54 NixOS x86_64 GNU/Linux

**Comment by cynicsketch** [comment]
Solved by https://github.com/cynicsketch/nix-mineral/pull/37 , although for anyone trying to troubleshoot the same error message some 10 years from now, we still have no clue what exactly causes it to be different for different machines.
