### ISSUE TITLE
Overrides of kernel param ignored

### ISSUE THREAD

**Issue by jbgi** [cynicsketch/nix-mineral#45]
Because overrides are merged before the main modules in the big `config = l.mkMerge [` their values come first in the kernel command line, but actually the kernel will only retains the last value from the command line, as per
https://github.com/torvalds/linux/blob/fc033cf25e612e840e545f8d5ad2edd6ba613ed5/arch/x86/boot/cmdline.c#L21-L23

A fast fix is too move the main module on top of the `config = l.mkMerge [` stack. Another, cleaner IMO, would be to handle overrides at the same location as default value.

**Comment by cynicsketch** [comment]
Would be resolved by https://github.com/cynicsketch/nix-mineral/issues/31

I didn't do a good job of explaining how this would work, but the idea is that all defaults (the so-called "main module") would be inside `config = l.mkMerge [ ...` and then all set by some arbitrary value like 

`nix-mineral.defaults.all = true;` = ```nix-mineral.defaults.sysctl = true; nix-mineral.defaults.boot-params = true; ..."
