### ISSUE TITLE
Use impermanence

### ISSUE THREAD

**Issue by cynicsketch** [cynicsketch/nix-mineral#9]
https://github.com/nix-community/impermanence
https://xeiaso.net/blog/paranoid-nixos-2021-07-18/
https://source.android.com/docs/security/features/verifiedboot

Building full system verified boot from the ground up for NixOS is a task best deligated to a far future when we still don't even have a stable secure boot implementation. In the meantime, a tmpfs on root can provide some of the same benefits (changes, i.e malicious, don't stick around). 

Though there are some potential risks, it's better than nothing. Should make optional or use mkDefault only since this may interfere with other user's impermenence configuraitons.

### Theoretical bypasses:
  * Direct attack on the `/nix/store` leads to malware being autoloaded anyways
  * Surreptitiously editing NixOS configuration to drop tmpfs on `/` and persist as is "typical" in the fstab
  * Putting malware in a persistent directory/file (persistent files can be signed on demand on other systems, on NixOS it's just assumed they are trustworthy.)
    * Could be mitigated by using sops-nix to declaratively set files like SSH keys(?)
  * Filesystem not obeying [W^X](https://en.wikipedia.org/wiki/W%5EX), if `/home` for example is writable freely but still executable, there is no point in putting malware elsewhere.

Most of these bypasses assume some knowledge of the NixOS system and would not work for blanket distribution of malware. Again, while this is better than nothing, ideally you'd have a system where an attacker can't get in even if they know exactly how the system works; security through obscurity (and really, not obscure either since you can just google all the info you want) is a bad model.

**Comment by wyyllou** [comment]
Just a note here, a tmpfs root needs quite a lot of ram, or your system can OOM a lot more often (i know from experience). Other impermanence implementations use a rollback btrfs/zfs snapshot system (i use zfs rollbacks), but it might be a little out of scope to include opinionated rollback configs here, although some people might find them useful, im not sure.

**Comment by wyyllou** [comment]
Relevant to my above comment, a module for zfs would look something like this: https://github.com/chaotic-cx/nyx/blob/main/modules/nixos/zfs-impermanence-on-shutdown.nix

**Comment by dr460nf1r3** [comment]
Can also do it via BTRFS: https://github.com/dr460nf1r3/dr460nixed/blob/main/nixos/modules/impermanence.nix#L19

**Comment by cynicsketch** [comment]
Closing since this is too complex for `nix-mineral` to address. Moving to https://github.com/cynicsketch/nix-mineral/issues/34
